version: 2
jobs:
  backend:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/florianehmke/plexname
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: ./go.test.sh
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test:
    jobs:
      - backend
